services:
  - type: web
    name: novo-bot
    env: python
    plan: free
    autoDeploy: true
    healthCheckPath: /
    buildCommand: "pip install -U pip && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
